// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrsjdjykigbewtyaygfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyc2pkanlraWdiZXd0eWF5Z2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzIyODcsImV4cCI6MjA2OTM0ODI4N30.-a5Sej-qukJB11KnZm5hqkDoXl-wSh-vh6EAs2AiSWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});